### ISSUE TITLE
Using Ubuntu's official worktree

### ISSUE THREAD

**Issue by thopiekar** [albfan/systemd-ubuntu-with-dbus#2]
I was looking for the repository were Ubuntu hosts its changes and finally found it on debian.
It would make our work much easier if we would create a new branch and just `git merge` on new upstream changes.

http://anonscm.debian.org/cgit/pkg-systemd/systemd.git/log/?h=ubuntu

PS: Made now a build recipe which only applies this commit https://github.com/thopiekar/systemd-ubuntu-with-dbus_for_miraclecast/commit/fc997128649719690a09f6a83c62ea72d9f306a8 and builds packages with Ubuntu's recent changes, see: https://code.launchpad.net/~thopiekar/+recipe/systemd+kdbus

**Comment by albfan** [comment]
Great!. I was looking for this but I can't find it.

I will drop all this repo commits and start from it.

Your commit is now really understandable (symbols for dbus feature), just tell me it compiles smoothly, because I have compiled version 219 7ubuntu2 from `apt-get source` and fails miserably.

**Comment by thopiekar** [comment]
I was also looking for it for a while and never expected to find it at Debian.

However, I use the codebase at Debian for Ubuntu, only applied this commit and it works well, as you can see in https://code.launchpad.net/%7Ethopiekar/+recipe/systemd+kdbus :)

You can try my packages by adding my PPA via:
- `sudo add-apt-repository ppa:thopiekar/miraclecast`
- `sudo apt-get update`
- `sudo apt-get upgrade`
- `sudo apt-get install miraclecast` .

`miraclecast` package content:

```
/.
/etc
/etc/dbus-1
/etc/dbus-1/system.d
/etc/dbus-1/system.d/org.freedesktop.miracle.conf
/usr
/usr/bin
/usr/bin/miracle-dhcp
/usr/bin/miracle-gst.sh
/usr/bin/miracle-sinkctl
/usr/bin/miracle-wifictl
/usr/bin/miracle-wifid
/usr/bin/miracled
/usr/share
/usr/share/doc
/usr/share/doc/miraclecast
/usr/share/doc/miraclecast/NEWS.gz
/usr/share/doc/miraclecast/README.Debian
/usr/share/doc/miraclecast/README.md.gz
/usr/share/doc/miraclecast/changelog.gz
/usr/share/doc/miraclecast/copyright
/usr/share/miraclecast
/usr/share/miraclecast/kill-wpa.sh
/usr/share/miraclecast/miracle-wifi.sh
/usr/share/miraclecast/normal-wifi.sh
/usr/share/miraclecast/show_wpa.sh
/usr/share/miraclecast/test_viewer.sh
/usr/share/miraclecast/wpa.conf
```

Just let me know if there is something missing :smile:

**Comment by albfan** [comment]
I have changed to debian upstream. And also point to your launchpad as easy install on README.md

**Comment by thopiekar** [comment]
:+1: 

Thank you for adding me to the email conversation btw.
