### ISSUE TITLE
unknown dpkg-buildpackage/debuild option: -ux

### ISSUE THREAD

**Issue by mnpenner** [albfan/systemd-ubuntu-with-dbus#4]
I tried following the instructions, but it says `-ux` isn't a valid option.

```
$ sudo debuild -uc -ux -i -rfakeroot            
debuild: unknown dpkg-buildpackage/debuild option: -ux
This package has a Debian revision number but there does not seem to be
an appropriate original tar file or .orig directory in the parent directory;
(expected one of systemd_219.orig.tar.gz, systemd_219.orig.tar.bz2,
systemd_219.orig.tar.lzma,  systemd_219.orig.tar.xz or systemd-ubuntu-with-dbus.orig)
continue anyway? (y/n) y
 dpkg-buildpackage -rfakeroot -D -us -uc -ux -i
dpkg-buildpackage: unknown option or argument -ux

Use --help for program usage information.
debuild: fatal error at line 1364:
dpkg-buildpackage -rfakeroot -D -us -uc -ux -i failed
```

**Comment by albfan** [comment]
Yes, sorry I noticed it a few weeks ago. I though I had changed it.

```
$ sudo debuild -uc -us -i -rfakeroot
```

Seems `-us` is added automatically anyway.

Please send a PR to own that correction.

**Comment by mnpenner** [comment]
Thanks. There's about 100 other errors that pop up after I get past that though. I'm giving up.

**Comment by albfan** [comment]
Ha ha ha. Yes, ubuntu is an overcomplicated distro for mere mortals (trying to build a package). There's a worflow based directly on git repo. Let me check if I can write a good guide and change this little mess.

**Comment by mevinbabuc** [comment]
The document still says $ sudo debuild -uc -ux -i -rfakeroot   

please change it to -us or remove it, if its not necessary
