### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by andreaconsole** [albfan/systemd-ubuntu-with-dbus#5]
On Ubuntu 14.04
After a lot of problems to solve all dependencies, I'm stuck with this error:

make --no-print-directory all-recursive
Making all in .
  CC       src/libsystemd/sd-bus/libsystemd_la-sd-bus.lo
gcc: error: 1/test": No such file or directory
make[2]: **\* [src/libsystemd/sd-bus/libsystemd_la-sd-bus.lo] Errore 1
make[1]: **\* [all-recursive] Errore 1
make: **\* [all] Errore 2

Could you help me?

**Comment by albfan** [comment]
First I would recommend you to change your mind an upgrade to ubuntu 14.10+. systemd is a big change for ubuntu. If official maintainers refuse to make transition before that version, is likely you cannot get it to work.

http://askubuntu.com/questions/490946/is-ubuntu-14-04-using-systemd

From your output I presume you are trying the typical (correct me if I'm wrong)

```
$ .configure &&  make && sudo make install
```

Steps to create a package for ubuntu are based on this file:

https://github.com/albfan/systemd-ubuntu-with-dbus/blob/master/debian/rules

and in that file you can only see the configurable part, there's a convention part (which for sure launches `make`) but in general you cannot make an ubuntu package issuing make.

Please reproduce all steps from clone till the command outputs that error. Let's see how far we can get.

**Comment by albfan** [comment]
I will close this as ubuntu 14.04 is not expected to work with systemd
