### ISSUE TITLE
dpkg-source: error: can't build with source format '3.0 (quilt)': no upstream tarball found at ../systemd_219.orig.tar.{bz2,gz,lzma,xz}

### ISSUE THREAD

**Issue by mevinbabuc** [albfan/systemd-ubuntu-with-dbus#7]
Unable to compile this from source. I keep getting this error.

dpkg-source: error: can't build with source format '3.0 (quilt)': no upstream tarball found at ../systemd_219.orig.tar.{bz2,gz,lzma,xz}

**Comment by albfan** [comment]
I have spend few hours to recover my ubuntu partition. I can check now all this crap and update this repo.

Are you using ubuntu 15.04 right?

**Comment by albfan** [comment]
Now README has instructions to build from repo (adding remotes where you can find pristine copy for your desired systemd version)

I will rebase this repo changes on top of last version of ubuntu vivid as soon as possible, if you can do it I will be pleased to merge that PR.

**Comment by albfan** [comment]
Can I close this issue?

**Comment by jmans25** [comment]
sorry to bump this, but I am getting a similar error as the OP.

```{bash}
gbp:error: Couldn't checkout "systemd_219.orig.tar.xz": execution failed: [Errno 2] No such file or directory
```

I am running this on a raspberry pi, OSMC, systemd 215. I have run apt-get dist-upgrade, and it doesn't upgrade the dbus version, so I have to make do. I think the OSMC team just has to do some more testing for this version before they update it. 

I branched "55ca9f9 (pristine-tar) pristine-tar data for systemd_215.orig.tar.xz"...
```{bash}
git branch pristine-tar 55ca9f9
```
...for my pristine TAR, and followed all other directions exactly. 

@albfan  Do you know if I'm doing anything wrong? Thanks, any help is appreciated :) 

Unrelated: Do you know if this is even necessary for OSMC on the Pi? Or is there an "embedded" branch somewhere I overlooked? 

__UPDATE__
So I read the following:
https://github.com/shadowsocks/shadowsocks-libev/issues/1382
and fixed my first problem by installing "pristine-tar" (`apt-get install pristine-tar`). But now I am getting another error:
```
gbp:error: Couldn't checkout "systemd_219.orig.tar.xz": it exited with 128
```
Do you know what I should do? Thanks!

**Comment by albfan** [comment]
@jmans25 you are looking to build systemd 215. This is for systemd 219. You need to change several things to make it work. Please open a different issue. Yours is compile "systemd 215 with kdbus"
