### ISSUE TITLE
git logg 81d67ad??

### ISSUE THREAD

**Issue by mone741120** [albfan/systemd-ubuntu-with-dbus#8]
Excuse me, I operate according to your instruction and stuck in "git logg 81d67ad"

git logg is not execute and show the following error:
git: 'logg' is not a git command. See 'git --help'.
Did you mean this?
    log

If I use the log to replace logg, 
and then the git has no "git-buildpackage", so I use "gbp buildpackage" to replace

is it right???

If it is right, and I solve some package dependency issue, I am in front of a new problem when executing "DEB_BUILD_OPTIONS=nocheck sbuild -d vivid -j4 systemd_*.dsc"

Package: systemd
Version: 219-7ubuntu6
Source Version: 219-7ubuntu6
Distribution: vivid
Machine Architecture: amd64
Host Architecture: amd64
Build Architecture: amd64

E: Chroot for distribution vivid, architecture amd64 not found
E: Error creating chroot

+------------------------------------------------------------------------------+
| Summary                                                                      |
+------------------------------------------------------------------------------+

Build Architecture: amd64
Build-Space: 0
Build-Time: 0
Distribution: vivid
Fail-Stage: create-session
Host Architecture: amd64
Install-Time: 0
Job: systemd_219-7ubuntu6.dsc
Machine Architecture: amd64
Package: systemd
Package-Time: 0
Source-Version: 219-7ubuntu6
Space: 0
Status: failed
## Version: 219-7ubuntu6

Finished at 20160629-1735
Build needed 00:00:00, 0k disc space
E: Error creating chroot

I will appreciate your help, thanks a lot

My platform is ubuntu 16.04 x64 on Virtualbox

**Comment by albfan** [comment]
Short answer:

https://launchpad.net/ubuntu/xenial/+source/systemd

Above systemd 220 kdbus comes enabled by default. You don't need to recompile systemd

Anyway you can only test miraclecast on a virtual machine with docker or similar.

https://github.com/albfan/miraclecast/issues/12
https://twitter.com/_TheMoses_/status/736881059246133248

Any testing on VM is appreciated to be updated on that miraclecast issue.

Long answer:

Oops!. Sorry 'git logg' is an alias from my toolchain

[my dot files](https://github.com/albfan/dotfiles/blob/master/gitconfig#L11)

[related response on stackoverflow](http://stackoverflow.com/a/22875140/848072)

You can install it on your system or write all the command.

Anyway, that command is only to confirm that hash is matching your systemd version.

That line is only an example. you need to use the hash of commit better matching your system. That is found using:

```
$ git log --oneline --decorate debian/pristine-tar
```

one of those commits is your pristine tar.

Provide a PR with a fix for README if you want, there we an discuss how to make instructions more clear.

**Comment by mone741120** [comment]
Thanks your reply.

I even seen some document which mentioned "Above systemd 220 kdbus comes enabled by default. You don't need to recompile systemd"

But when I follow your instruction about "miraclecast" and compile by "make", I face a problem as listed:

<pre>
/home/lyhsiao/workspace/miraclecast-master/src/shared/rtsp.c:31:30: fatal error: systemd/sd-event.h: No such file or directory
compilation terminated.
src/shared/CMakeFiles/miracle-shared.dir/build.make:62: recipe for target 'src/shared/CMakeFiles/miracle-shared.dir/rtsp.c.o' failed
make[2]: *** [src/shared/CMakeFiles/miracle-shared.dir/rtsp.c.o] Error 1
CMakeFiles/Makefile2:151: recipe for target 'src/shared/CMakeFiles/miracle-shared.dir/all' failed
make[1]: *** [src/shared/CMakeFiles/miracle-shared.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
</pre>

I found the previously close issue "Missing sd-event.h on Debian testing #21", and the solution of this issue is "You need to get a systemd with kdbus enabled." So I try to recompile the systemd.

Could you give some guide to solve this problem?? Thank you very much!!!!

PS. I had check the systemd version of Ubuntu 1604 x64 is 229

**Comment by albfan** [comment]
These command should stop at first problem detected.

```
$ ./autogen.sh && ./configure && make && sudo make install
```

Did you install dev package for systemd?. On ubuntu source and binaries come from different packages

```
$ sudo apt-get install libsystemd-dev
```

should be enough.

Install check package if you want to try `make check` before install

**Comment by mone741120** [comment]
I appreciated your time.

I installed libsystemd-dev and libreadline-dev, and then the error are showed as listed when I compile:

> [ 18%] Built target miracle-shared
> [ 24%] Built target miracled
> [ 40%] Built target miracle-wifid
> [ 56%] Built target miracle-dhcp
> [ 67%] Built target miracle-wifictl
> [ 83%] Built target miracle-sinkctl
> -lpthread
> [ 86%] Linking C executable test_wpas
> /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcheck_pic.a(check_pack.o): undefined reference to symbol '__pthread_unregister_cancel@@GLIBC_2.3.3'
> //lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
> collect2: error: ld returned 1 exit status
> test/CMakeFiles/test_wpas.dir/build.make:95: recipe for target 'test/test_wpas' failed
> make[2]: **\* [test/test_wpas] Error 1
> CMakeFiles/Makefile2:468: recipe for target 'test/CMakeFiles/test_wpas.dir/all' failed
> make[1]: **\* [test/CMakeFiles/test_wpas.dir/all] Error 2
> Makefile:127: recipe for target 'all' failed
> make: **\* [all] Error 2

How do I fix this error? I am very grateful to you.

UPDATE: 
I try to modify the /miraclecast-master/test/CMakeList.txt
and add the following line on bottom.

> find_package(Threads)
> set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -lpthread")
> target_link_libraries(test_wpas -lpthread)
> target_link_libraries(test_rtsp -lpthread)
> target_link_libraries(test_valgrind -lpthread)

Finally, I can make miraclecast successfully, and then I will check it work or not between two VM.

If my modifications are unsuitable, please point it for me. Thanks a lot.

**Comment by albfan** [comment]
Great, can you provide a PR on miraclecast about that? would be useful for many others.

**Comment by mone741120** [comment]
I have provide a PR on miraclecast.

It does not seem to work on VirtualBox Guest without any actual wireless card adapter.

`sudo miracle-wifid &`

> [1] 3271
> ERROR: dbus: cannot claim org.freedesktop.miracle.wifi bus-name: -13 (manager_dbus_connect() in /home/lyhsiao/workspace/miraclecast-master/src/wifi/wifid-dbus.c:898)

`sudo miracle-sinkctl`

> ERROR: cannot retrieve objects: The name org.freedesktop.miracle.wifi was not provided by any .service files (ctl_wifi_fetch() in /home/lyhsiao/workspace/miraclecast-master/src/ctl/ctl-wifi.c:1103)
> [miraclectl] # 

So Do I  just need to use the real wireless card adapter to try???

**Comment by albfan** [comment]
About working on virtual machines you can collaborate on specific issue about it on miraclecast

albfan/miraclecast#12

Seems that virtual machines do not access directly to hardware (and emulate it with less features), so to use a virtual environment new solutions like docker:

https://twitter.com/_TheMoses_/status/736881059246133248

About test between virtual machines you need to collaborate in another unfinishes task:

https://github.com/albfan/miraclecast/issues/4

See that Q&D works, just it is not implemented, should be easy to do.

**Comment by mone741120** [comment]
Thanks your reply, 
Maybe I should test my build on real machine, because I want to know my issues occurred on VM will happen on real machine or not~

**Comment by albfan** [comment]
Can I close this issue?
