### ISSUE TITLE
Compile systemd 215 with kdbus - exited with 128

### ISSUE THREAD

**Issue by jmans25** [albfan/systemd-ubuntu-with-dbus#9]
I'm a raspberry pi user on systemd 215. I get the following error when compiling the Debs: 

```{bash}
gbp:error: Couldn't checkout "systemd_219.orig.tar.xz": execution failed: [Errno 2] No such file or directory
```

I am running this on a raspberry pi, OSMC, systemd 215. I have run apt-get dist-upgrade, and it doesn't upgrade the dbus version, so I have to make do. I think the OSMC team just has to do some more testing for this version before they update it. 

I branched "55ca9f9 (pristine-tar) pristine-tar data for systemd_215.orig.tar.xz"...
```{bash}
git branch pristine-tar 55ca9f9
```
...for my pristine TAR, and followed all other directions exactly. 

@albfan  Do you know if I'm doing anything wrong? Thanks, any help is appreciated :) 

Unrelated: Do you know if this is even necessary for OSMC on the Pi? Or is there an "embedded" branch somewhere I overlooked? 

__UPDATE__
So I read the following:
https://github.com/shadowsocks/shadowsocks-libev/issues/1382
and fixed my first problem by installing "pristine-tar" (`apt-get install pristine-tar`). But now I am getting another error:
```
gbp:error: Couldn't checkout "systemd_219.orig.tar.xz": it exited with 128
```
Do you know what I should do? Thanks!

**Comment by jmans25** [comment]
__UPDATE__
GOT IT! After doing some research (https://wiki.debian.org/PackagingWithGit#pristine-tar), I found out that the `--git-pristine-tar` option must be added to the `git-buildpackage` command. To recap:
The following step on in the README.md file:
```{bash}
#THIS IS THE INCORRECT COMMAND!!
git-buildpackage -S -us -uc -nc
```
Becomes:
```{bash}
git-buildpackage -S -us -uc -nc --git-pristine-tar
```
To get rid of the error.
Closing now.

**Comment by albfan** [comment]
Great. Are trying miraclecast with this?

**Comment by jmans25** [comment]
@albfan Yes, and it installed! 
I had to use your systemd 219 branch though:
```
git clone -b systemd-219 https://github.com/albfan/miraclecast.git
```
Then, to quote the Wiki:
```
  $ ./autogen.sh
  $ mkdir build
  $ ../configure
  $ make
  $ make install
```

**Comment by albfan** [comment]
Fantastic!. Share some photos if possible, I will tweet about it!

**Comment by jmans25** [comment]
sure, as soon as I actually get the program working lol
Compiling+installing it is one thing, actually running it is another :/
So far I know my card is compatible with it (TP-LINK TL-WN725N v2  rtl8188eu) but I can't get it working since iw won't detect it:(
Thats another topic for another post lol. But I noticed that tomerf (https://github.com/tomerf) got it working: https://github.com/albfan/miraclecast/issues/148. I gotta ask him what he did.

**Comment by albfan** [comment]
You can open an issue on miraclecast. See wiki fir info about logs to collect to get support
